"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Award, BriefcaseBusiness, Code2, Copy, GitFork, GraduationCap, Mail, MapPin, Phone, Sparkles, Terminal, Layers3, Braces, Database, Wrench } from "lucide-react";
import { motion, useScroll, useSpring } from "motion/react";
import { Navbar } from "@/components/navbar";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { ProjectCard } from "@/components/project-card";
import { contact, projects, skillGroups } from "@/data/portfolio";

const icons = [Braces, Layers3, Terminal, Database, Wrench, Code2];
export default function Home() {
  const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 120, damping: 24 });
  const [copied, setCopied] = useState(false); const [top, setTop] = useState(false);
  useEffect(() => { const onScroll = () => setTop(scrollY > 700); addEventListener("scroll", onScroll); return () => removeEventListener("scroll", onScroll); }, []);
  const copyEmail = async () => { await navigator.clipboard.writeText(contact.email); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  return <><motion.div className="scroll-progress" style={{ scaleX }}/><Navbar/><main>
    <section id="Home" className="hero section-shell">
      <div className="hero-glow"/><div className="hero-grid"/>
      <motion.div className="hero-copy" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}>
        <span className="availability"><i/>Open to software opportunities</span><p className="hero-kicker">HO CHI MINH CITY · VIETNAM</p>
        <h1>Hi, I&apos;m <span>Quyen.</span></h1><div className="role"><span>Fresher Software Developer</span><i/></div>
        <p className="hero-intro">I build modern web applications with React.js, Node.js, and MongoDB, turning ideas into functional, user-friendly digital experiences.</p>
        <div className="hero-actions"><a className="button primary" href="#Projects">View my projects</a><a className="button ghost" href={`mailto:${contact.email}`}><Mail/>Get in touch</a></div>
        <div className="social-row"><a href={contact.github} target="_blank" rel="noreferrer"><GitFork/>github.com/quyenhoang0712</a><a href={`mailto:${contact.email}`}><Mail/>{contact.email}</a></div>
      </motion.div>
      <div className="code-orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="code-card"><div className="code-head"><i/><i/><i/></div><pre><b>const</b> developer = &#123;{`\n`}  name: <em>&quot;Quyen&quot;</em>,{`\n`}  focus: <em>&quot;Full-stack&quot;</em>,{`\n`}  status: <em>&quot;Building&quot;</em>{`\n`}&#125;;</pre><span className="cursor">_</span></div><span className="float-tag tag-react">React</span><span className="float-tag tag-node">Node.js</span><span className="float-tag tag-db">MongoDB</span></div>
      <a className="scroll-cue" href="#About"><span>Scroll to explore</span><ArrowDown/></a>
    </section>
    <section id="About" className="section-shell content-section"><Reveal><SectionHeading eyebrow="01 / ABOUT" title="Turning ideas into reliable software."/></Reveal><div className="about-grid"><Reveal className="about-copy"><p>I&apos;m a software developer with hands-on experience building full-stack web applications and frontend development experience at Patecan. I enjoy developing responsive interfaces, integrating RESTful APIs, and solving real-world problems through software.</p><p>My technical background includes React.js, Node.js, Express.js, and MongoDB. I&apos;m actively improving my engineering skills and looking for opportunities to grow as a professional software developer.</p></Reveal><div className="highlights">{[[BriefcaseBusiness,"Frontend internship","Real team experience at Patecan"],[Layers3,"Full-stack development","Products built from interface to database"],[Terminal,"API integration","Dynamic data through RESTful services"]].map(([Icon,title,desc],i) => <Reveal key={title as string} delay={i*.08}><div className="highlight"><Icon/><div><h3>{title as string}</h3><p>{desc as string}</p></div><span>0{i+1}</span></div></Reveal>)}</div></div></section>
    <section id="Skills" className="section-shell content-section"><Reveal><SectionHeading eyebrow="02 / TOOLKIT" title="Technologies I work with." copy="A practical toolkit built through coursework, internship experience, and end-to-end projects."/></Reveal><div className="skills-grid">{skillGroups.map((group,i) => { const Icon=icons[i]; return <Reveal key={group.title} delay={(i%3)*.06}><article className="skill-card"><div className="skill-icon"><Icon/></div><h3>{group.title}</h3><div>{group.skills.map(x=><span key={x}>{x}</span>)}</div></article></Reveal>})}</div></section>
    <section id="Experience" className="section-shell content-section"><Reveal><SectionHeading eyebrow="03 / EXPERIENCE" title="Learning in a real product team."/></Reveal><Reveal><article className="experience-card"><div className="experience-meta"><span>APR — JUN 2025</span><i/></div><div><span className="company">PATECAN</span><h3>Frontend Developer Intern</h3><p>Contributed to existing products with React.js and collaborated around backend-provided APIs.</p><ul>{["Developed frontend features using React.js.","Integrated RESTful APIs provided by the backend development team.","Maintained and improved existing user interfaces.","Handled API responses and displayed dynamic data.","Updated reusable React components to support additional functionality."].map(x=><li key={x}>{x}</li>)}</ul></div></article></Reveal></section>
    <section id="Projects" className="section-shell content-section projects-section"><Reveal><SectionHeading eyebrow="04 / SELECTED WORK" title="Products built beyond the tutorial." copy="Three full-stack systems that explore community, education, and project operations."/></Reveal><div className="projects-list">{projects.map((p,i)=><Reveal key={p.name}><ProjectCard project={p} index={i}/></Reveal>)}</div></section>
    <section id="Education" className="section-shell content-section"><Reveal><SectionHeading eyebrow="05 / EDUCATION" title="Building a strong foundation."/></Reveal><div className="education-grid"><Reveal><article className="education-card"><GraduationCap/><div><span>2021 — PRESENT · EXPECTED 2027</span><h3>Computing</h3><h4>Greenwich Vietnam</h4><p>Completed software development and information technology coursework, with practical experience developing academic and personal web applications.</p></div></article></Reveal><Reveal delay={.1}><article className="cert-card"><Award/><div><span>CERTIFICATION</span><h3>APTIS ESOL</h3><p>CEFR B2 English Proficiency</p></div></article></Reveal></div></section>
    <section id="Contact" className="section-shell contact-section"><Reveal><div className="contact-panel"><span className="contact-label"><Sparkles/>Available for new opportunities</span><h2>Let&apos;s build something <span>together.</span></h2><p>I&apos;m open to Fresher Software Developer, Frontend Developer, and Full-stack Developer opportunities.</p><div className="contact-actions"><a className="button primary" href={`mailto:${contact.email}`}><Mail/>Email me</a><a className="button ghost" href={contact.github} target="_blank" rel="noreferrer"><GitFork/>GitHub</a></div><div className="contact-details"><span><MapPin/>{contact.location}</span><a href={`tel:${contact.phone}`}><Phone/>{contact.phone}</a><button onClick={copyEmail}><Copy/>{copied ? "Email copied!" : contact.email}</button></div></div></Reveal></section>
  </main><footer><div><a className="logo" href="#Home">HQ<span>.</span></a><p>© 2026 Hoang Quang Quyen. Built with React.</p><a href={contact.github} target="_blank" rel="noreferrer"><GitFork/>GitHub</a></div></footer>{top && <button className="back-top" onClick={()=>scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top"><ArrowUp/></button>}</>;
}
